name: Build-IMCI-APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Buildozer
        uses: ArtemSerebrennkov/buildozer-action@v1
        with:
          command: buildozer -v android debug
      - name: Save APK
        uses: actions/upload-artifact@v2
        with:
          name: IMCI-Yemen-APK
          path: bin/*.apk
